exclude: '^docs/conf.py|.*references/.*'

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: fix-encoding-pragma
  - id: mixed-line-ending
    # args: ['--fix=no']
    args: ['--fix=auto']
  - id: end-of-file-fixer
  # - id: requirements-txt-fixer
  - id: flake8
    args: ['--max-line-length=90']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
